### ISSUE TITLE
Children don't update their base styles

### ISSUE THREAD

**Issue by smirea** [felipethome/react-inline-transition-group#4]
Awesome rewrite! It's getting there
One issue I'm having now in v2.0 is that if children update their styles, their props don't get updated.

Example:

```jsx
class TransitionTest extends PureComponent {

    state = { size: 100 }

    render () {
        const {size} = this.state;
        console.log('--->', size)
        return (
        <Transition
            onClick={() => console.log('here') || this.setState({size: 50 + Math.random() * 100 | 0})}
            style={{position: 'absolute', top: 10, left: 10}}
        >
            <div style={{backgroundColor: 'red', width: size, height: size}} />
            <Test style={{backgroundColor: 'red', width: size, height: size}} />
        </Transition>
        );
    }

}
```

clicking the container does nothing even thought `render()` is called with the updated info. If you replace the `Transition` wrapper with a `<div>` it works as expected

**Comment by felipethome** [comment]
Yes, when I was rewriting I notice that would happen, but I still don't know what would be the best solution. Here is the problem:

Your styles are actually a merge between the base, current phase, props.style (the priority grows from left to right). So in your example it is ok if I just update the styles, but imagine you have also the appear style defined.

    appear = {
      background: '#F00',
      transition: 'all 1s',
    }

and your child component is:

    <div style={{height: '100px', background: '#0F0'}} />

Your result style for that child would be:

    mergedStyle = {
      background: '#0F0',
      height: '100px',
      transition: 'all 1s'
    }

Now, if you change your props.style to:

    <div style={{height: '100px', background: '#00F'}} />

The new mergedStyle will be:

    mergedStyle = {
      background: '#00F',
      height: '100px',
      transition: 'all 1s'
    }

That means your style will change, but will change with a transition. In other words, it will not just instantly change, it will have a transition from `#0F0` to `#00F`. This behavior it is also what would happen without React, using just Javascript, if you have transitions present in the styles.

So, or I track when the props changed and eliminate the transitions in this situation or I just let it suffer the transition. Still trying to figure out what would be the best for the user.

**Comment by smirea** [comment]
hmm cancelling/changing the transition when styles change is not that intuitive since the transition events don't actually depend on the styles per se

The issue seems to stem from the priority of the different sources of truth. If you change the order to `base`, `props`, `phase` this might fix the issue. The use-case generally is that component styles and base styles are, for the most part, fixed.
That way you only have an issue if styles change during a transition which is a much less common case.

So in your example:

merge 1 styles would be:

```jsx
mergedStyle = {
  background: '#F00',
  height: '100px',
  transition: 'all 1s'
}
```

after the change, the component style props get updated to 

```jsx
<div style={{height: '100px', background: '#00F'}} />
````

so the new styles will be the same:

```jsx
mergedStyle = {
  background: '#F00',
  height: '100px',
  transition: 'all 1s'
}
```

The expectation being that if an element is in a given state, other than the base state, then the state styles are final

**Comment by felipethome** [comment]
The order you suggested for merging is what the previous version used to do, but then I thought: maybe would be better to let the user overwrite the styles even for the phases if he set props.style.

But maybe since this is a "group" of components, it should have a limited way the users could overwrite the styles and this limitation should be as you said:

> The expectation being that if an element is in a given state, other than the base state, then the state styles are final

This doesn't solve the problem entirely though. The transition property can be present in the base styles.

    base = {
      background: '#F00',
      transition: 'all 1s'
    }

One style object like this means that no transition will happen when the DOM nodes are being created for the first time (because the browser doesn't make transitions for DOM nodes that are being inserted in the tree, just for the ones that are being updated), but a transition will happen if you change it's style after created, for example using props.style.

But, maybe this makes sense for the user?

**Comment by felipethome** [comment]
> The expectation being that if an element is in a given state, other than the base state, then the state styles are final

Another thing about this is that if the user changes the appear or enter styles, he is taking the risk of having half of the elements with a different style from the others. In other words, components that were added before the style change will continue with the old style.

**Comment by felipethome** [comment]
If I remove the base style and explain to the user that the initial styles should be in the props.style of the child component that would solve everything.

**Comment by smirea** [comment]
> One style object like this means that no transition will happen when the DOM nodes are being created for the first time (because the browser doesn't make transitions for DOM nodes that are being inserted in the tree, just for the ones that are being updated), but a transition will happen if you change it's style after created, for example using props.style.

Yes if you only have:

```jsx
<Transition base={{...}}>
    <div />
</Transition>
```

nothing should happen, and it makes sense. The base styles don't mean anything, it's just a starting point

Even if you add child props:

```jsx
<Transition base={{...}}>
    <div style={...} />
</Transition>
```

Still nothing should happen. You're still in your default state, just that the child props should extend the base props. Transition should only happen if you define a transition state: `appear` `enter` `leave`

Effectively what I'm saying is to treat the `base` state as a shortcut to passing props to all the children as to prevent people doing:

```jsx
const childStyles = {foo: 1}
<Transition>
    <div style={childStyles} />
    <div style={childStyles} />
    <div style={childStyles} />
    <div style={childStyles} />
    <div style={childStyles} />
</Transition>
```

So have it be a helper and nothing else. The above would be annoying to write, so `base` to the rescue!

**Comment by felipethome** [comment]
I was thinking and the merge order doesn't solve the problem. Suppose you do the merge in this order: `baseStyle`, `props.style`, `phaseStyle`. You still would have problems with transitions, because, even if the CSS transition property is in the `phaseStyle` and that the `phaseStyle` has a higher priority, the `props.style` can still introduce changes if it has CSS properties that are not present in the `phaseStyle`.

Also, I need to clarify, there is no such thing as base phase (in the README I wrote like if it was). All components that are inside ReactInlineTransitionGroup will face the appear/enter phase. Even if you do not set the styles for these phases they will still occur (is part of their semantics, because the component appeared/entered after all).

Now, back to our problem: what to do if one of the style objects (base, appear, enter, leave, props.style) changes?

1. You could not update child components that are already inside the main component and just new ones will suffer the changes. It is like if anything already inside the main component is immutable. This is the current approach ReactInlineTransitionGroup uses.

2. You could update all of them, even the ones that are still in the transition process.

3. You could try to update without using the transition for the ones that are already inside the group.

**About the second possibility:**

This is probably the best solution. If the user decides he doesn't want to use the same style anymore everything should be reinitialized. The user needs to understand the styles of a child are the result of merging `baseStyle`, `phaseStyle` and `props.style` so if he changes one of these style objects everything that is already inside the group needs to reflect this new state (this is what normally React components do, the only difference here is that mine has transitions).

So, for example, If he changes just `props.style` and the CSS transition property of the phase the child component is doesn't map a transition to the CSS properties that will change so the update will happen instantly, but if the phase has a CSS transition property that maps this changes so a new transition will happen (of course, the user could set the CSS transition property to `none`).

I consider this to be what any React component should do when receiving new props and that the user must understand that the props he changes affects the children in the parent component and that how they are affected depends on the behavior of the parent component itself.

What to do if the component is in the middle of a transition?
Don't need to worry.

**About the third possibility:**

What to do with components that are already inside the group?
Update them without using the transition. So, would need to unset the transition properties.

What to do if the component is in the middle of a transition? 
Could wait until the transition process finishes and then update to the new style without using the transition, but this would be completely unnatural.

---

Another thing, ReactCSSTransitionGroup should not be faced as an implementation reference, but if you look at their approach you will see that styles of old children can never change, and you are even far limited because of using CSS classes. But, of course, you could use the style property in your children and since inline style has the highest priority between the ways you can define styles, they will be applied, but they will trigger a transition if you defined so in your CSS classes.

This behavior of ReactCSSTransitionGroup is kind of what I'm suggesting in item 2, but my approach has the advantage that instead of just dynamic changing the style attribute of your child, you could also change the `phaseStyle` if you want.

**Comment by felipethome** [comment]
I'm closing this, because I implemented the item 2 approach I described above in version 2.1.1.
